resource_group_name = "rg-se-webapp-dev"
location            = "West Europe"
app_service_plan_name = "asp-se-webapp-dev"
app_service_name    = "app-se-webapp-dev"
storage_account_name= "stterraformbackend"
storage_container_name= "terraform-state"
