apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-webapi
  template:
    metadata:
      labels:
        app: azure-webapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-webapi
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-webapi
spec:
  ports:
  - port: 6379
  selector:
    app: azure-webapi
---
