name: Build aks Web App

permissions:
  id-token: write
  contents: read

on: 
  workflow_call:  
    inputs:    
      environment:
         description: The name of the environment to deploy to
         required: true
         type: string 
      ref:
         description: The name of the ref to to deploy from 
         required: true
         type: string
      resource_group_name:
         description: The name of the resource group to use
         required: true
         type: string
      registry_name:
         description: The name of the registry to use
         required: true
         type: string
      repository_name:
         description: The name of the repository to use
         required: true
         type: string
      cluster_name: 
         description: The name of the cluster to use
         required: true
         type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AKS_CLIENT_ID:
        required: true
      AKS_SECRET_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
   build:
    name: Build AKS Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}          
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}          
          arm_use_oidc: true

      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: '${{ inputs.registry_name }}'
          repository: '${{ inputs.repository_name }}'
          image:  azure-aks-webapi
          folder: Webapi
          branch: master
          tag: ${{ github.sha }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ inputs.resource_group_name }}' 
          cluster-name: '${{ inputs.cluster_name }}'
