name: Build Web App

on: 
  workflow_call:  
    inputs:  
      dotnet_version:
         description: The version of .NET Core to use
         required: true
         type: string
      artifact_name:
         description: The name of the artifact to use
         required: true
         type: string

jobs:
   build:
    name: Build Web App
    runs-on: windows-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/${{ inputs.artifact_name }}

    outputs:
      publish_path: ${{ github.workspace }}/${{ inputs.artifact_name }}
