name: DeploymentWebApp

permissions:
  id-token: write
  contents: read

on: 
  workflow_call:  
    inputs:    
      environment:
         description: The name of the environment to deploy to
         required: true
         type: string 
      ref:
         description: The name of the ref to to deploy from 
         required: true
         type: string
      dotnet_version:
         description: The version of .NET Core to use
         required: true
         type: string        
      artifact_name:
         description: The name of the artifact to use
         required: true
         type: string
      webapp_name:
         description: The name of the webapp to deploy
         required: true
         type: string
      location:
         description: The location to deploy to
         required: true
         type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
   deploy:
    name: Deploy Web App
    runs-on: windows-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
            name: build-artifact
            path: ${{ inputs.artifact_name }}

      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            app-name: ${{ inputs.webapp_name }}
            package: ${{ inputs.artifact_name }}
            slot-name: production
