name: DeploymentWebApp

permissions:
  id-token: write
  contents: read

on: 
  workflow_call:  
    inputs:    
      environment:
         description: The name of the environment to deploy to
         required: true
         type: string 
      ref:
         description: The name of the ref to to deploy from 
         required: true
         type: string
      resource_group_name:
         description: The name of the resource group to use
         required: true
         type: string
      registry_name:
         description: The name of the registry to use
         required: true
         type: string
      repository_name:
         description: The name of the repository to use
         required: true
         type: string
      cluster_name: 
         description: The name of the cluster to use
         required: true
         type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AKS_CLIENT_ID:
        required: true
      AKS_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
   deploy:
    name: Deploy aks Web App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AKS_CLIENT_ID }}
          client-secret: ${{ secrets.AKS_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             azure-webapi-in-one-redis.yaml
          images: '${{ inputs.registry_name }}.azurecr.io/${{ inputs.registry_name.repository_name }}/azure-vote-front:${{ github.sha }}'
          pull-images: false
