name: DeploymentTerraform

permissions:
  id-token: write
  contents: read

on: 
  workflow_call:  
    inputs:    
      environment:
         description: The name of the environment to deploy to
         required: true
         type: string 
      ref:
         description: The name of the ref to to deploy from 
         required: true
         type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
   deploy:
    name: Deploy Web App
    runs-on: windows-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - run: echo ${{ secrets.AZURE_CLIENT_ID }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.5.0 
            terraform_wrapper: false

      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: terraform
        

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        working-directory: terraform
      