name: main_aks_webapp
on:
  push:
    branches: [ "main" ]    
    paths: ["Webapi/**"]
  pull_request:

env:
  RESOURCE_GROUP_NAME: 'rg-se-aks-'
  LOCATION: 'westus'
  registry: 'aksreg'
  repository: 'githubworkflows' 
  cluster_name: 'aks-se-webapi'

permissions:
      id-token: write
      contents: read
jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
      location: ${{ env.LOCATION }}
      registry: ${{ env.registry }}
      repository: ${{ env.repository }}
      cluster_name: ${{ env.cluster_name }}
    steps:
      - run: echo "Exposing env vars"
  
  build-AKS_workflow: 
    permissions:
      id-token: write
      contents: read
    needs: [vars]
    strategy:
      matrix:
        target: [dev]  
    uses: ./.github/workflows/build-aks-webapp.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: '${{ needs.vars.outputs.resource_group_name }}${{ matrix.target }}'
      registry_name: '${{ needs.vars.outputs.registry }}'
      repository_name: '${{ needs.vars.outputs.repository }}'
      cluster_name: '${{ needs.vars.outputs.cluster_name }}'
    secrets: inherit # pass all secrets

  deploy-AKS-workflow-dev:
    permissions:
      id-token: write
      contents: read
    needs: [vars, build-AKS_workflow]
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-aks-webapp.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: '${{ needs.vars.outputs.resource_group_name }}'
      registry_name: '${{ needs.vars.outputs.registry }}'
      repository_name: '${{ needs.vars.outputs.repository }}'
      cluster_name: '${{ needs.vars.outputs.cluster_name }}'
    secrets: inherit # pass all secrets

