name: Main Terraform

on:
  push:
    branches: [ "main" ]
    paths: ["terraform/resources/**"]
  pull_request:

# env:
#   DOTNET_VERSION: '8.0.x'
#   AZURE_WEBAPP_NAME: 'WorkFlow'    # set this to the name of your Azure Web App
#   AZURE_WEBAPP_PACKAGE_PATH: '.'     # set this to the path to your web app project, defaults to the repository roo  
#   ArtifactName: 'WorkFlow' 


jobs:
  build-workflow: 
    uses: ./.github/workflows/build-terraform.yml   

  deploy-backendworkflow-dev:  
    permissions:
      id-token: write
      contents: read
    needs: build-workflow
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-backend-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
    secrets: inherit # pass all secrets

  deploy-workflow-dev:  
    permissions:
      id-token: write
      contents: read
    needs: deploy-backendworkflow-dev
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
    secrets: inherit # pass all secrets


  deploy-workflow-Test:
    permissions:
      id-token: write
      contents: read
    needs: deploy-workflow-dev
    strategy:
      matrix:
        target: [Test]
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
    secrets: inherit # pass all secrets

    
