name: Main AKS
on:
  push:
    branches: [ "main" ]
    paths: ["terraform/resources_aks/**"] 

env:
  RESOURCE_GROUP_NAME: 'rg-se-aks-'
  LOCATION: 'eastus'
  STORAGE_ACCOUNT_NAME: 'stseaks'
  CONTAINER_NAME: 'terraform-state' # CONTAINER_NAME

permissions:
      id-token: write
      contents: read
jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
      location: ${{ env.LOCATION }}
      storage_account_name: ${{ env.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ env.CONTAINER_NAME }}
      
    steps:
      - run: echo "Exposing env vars"
  
  build-workflow: 
    uses: ./.github/workflows/build-terraform.yml  

  deploy-aks-cluster-workflow-dev:    
    permissions:
      id-token: write
      contents: read
    needs: [vars, build-workflow]
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-aks.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: '${{ needs.vars.outputs.resource_group_name }}${{ matrix.target }}'
      location: '${{ needs.vars.outputs.location }}'
      storage_account_name: '${{ needs.vars.outputs.storage_account_name }}${{ matrix.target }}'
      container_name: '${{ needs.vars.outputs.container_name }}${{ matrix.target }}'      
    secrets: inherit # pass all secrets

