name: Main Terraform

on:
  push:
    branches: [ "main" ]
    paths: ["terraform/resources/**"]  

env:
  RESOURCE_GROUP_NAME: 'rg-se-terrraform-dev'
  LOCATION: 'westeurope'
  STORAGE_ACCOUNT_NAME: 'stseterraformdev'
  CONTAINER_NAME: 'terraform-state' # CONTAINER_NAME

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
      location: ${{ env.LOCATION }}
      storage_account_name: ${{ env.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ env.CONTAINER_NAME }}
    steps:
      - run: echo "Exposing env vars"
  
  build-workflow: 
    uses: ./.github/workflows/build-terraform.yml   


  # deploy-backendworkflow-dev:  
  #   permissions:
  #     id-token: write
  #     contents: read
  #   needs: build-workflow
  #   strategy:
  #     matrix:
  #       target: [dev]   
  #   uses: ./.github/workflows/deployment-backend-terraform.yml
  #   with:
  #     environment: ${{ matrix.target }}
  #     ref: '${{ github.ref }}'
  #     resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
  #     location: ${{ env.LOCATION }}
  #     storage_account_name: ${{ env.STORAGE_ACCOUNT_NAME }}
  #     container_name: ${{ env.CONTAINER_NAME }}
  #   secrets: inherit # pass all secrets

  deploy-workflow-dev:    
    permissions:
      id-token: write
      contents: read
    needs: [vars, build-workflow]
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: ${{ needs.vars.outputs.resource_group_name }}
      location: ${{ needs.vars.outputs.location }}
      storage_account_name: ${{ needs.vars.outputs.storage_account_name }}
      container_name: ${{ needs.vars.outputs.container_name }}
    secrets: inherit # pass all secrets


  deploy-workflow-Test:
    permissions:
      id-token: write
      contents: read
    needs: [vars, deploy-workflow-dev]
    strategy:
      matrix:
        target: [Test]
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: ${{ needs.vars.outputs.resource_group_name }}
      location: ${{ needs.vars.outputs.location }}
      storage_account_name: ${{ needs.vars.outputs.storage_account_name }}
      container_name: ${{ needs.vars.outputs.container_name }}
    secrets: inherit # pass all secrets

    
