name: Main Terraform

on:
  push:
    branches: [ "main" ]
    paths: ["terraform/resources/**"]  

env:
  RESOURCE_GROUP_NAME: 'rg-se-webapp-dev'
  LOCATION: 'westeurope'
  STORAGE_ACCOUNT_NAME: 'stterraformbackend'
  CONTAINER_NAME: 'terraform-state' # CONTAINER_NAME

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      user: ${{ env.RESOURCE_GROUP_NAME }}
    steps:
      - run: echo "Exposing env vars ${{ vars.outputs.user }}"
  
  build-workflow: 
    needs: vars
    uses: ./.github/workflows/build-terraform.yml   
    with:
      user: ${{ needs.vars.outputs.user }}

  # deploy-backendworkflow-dev:  
  #   permissions:
  #     id-token: write
  #     contents: read
  #   needs: build-workflow
  #   strategy:
  #     matrix:
  #       target: [dev]   
  #   uses: ./.github/workflows/deployment-backend-terraform.yml
  #   with:
  #     environment: ${{ matrix.target }}
  #     ref: '${{ github.ref }}'
  #     resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
  #     location: ${{ env.LOCATION }}
  #     storage_account_name: ${{ env.STORAGE_ACCOUNT_NAME }}
  #     container_name: ${{ env.CONTAINER_NAME }}
  #   secrets: inherit # pass all secrets

  deploy-workflow-dev:  
    permissions:
      id-token: write
      contents: read
    needs: build-workflow
    strategy:
      matrix:
        target: [dev]   
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: "$RESOURCE_GROUP_NAME"
      location: $LOCATION
      storage_account_name: $STORAGE_ACCOUNT_NAME
      container_name: $CONTAINER_NAME
    secrets: inherit # pass all secrets


  deploy-workflow-Test:
    permissions:
      id-token: write
      contents: read
    needs: deploy-workflow-dev
    strategy:
      matrix:
        target: [Test]
    uses: ./.github/workflows/deployment-terraform.yml
    with:
      environment: ${{ matrix.target }}
      ref: '${{ github.ref }}'
      resource_group_name: "$RESOURCE_GROUP_NAME"
      location: $LOCATION
      storage_account_name: $STORAGE_ACCOUNT_NAME
      container_name: $CONTAINER_NAME
    secrets: inherit # pass all secrets

    
