# name: Create Storage Account

# permissions:
#     id-token: write
#     contents: read
# on:
#   push:
#     branches: [ "main" ]
#     paths: ["terraform/storage/**"]
#   pull_request:

# jobs:
#   create-storage:
#     runs-on: windows-latest    

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.0

#       - name: Validate Terraform
#         run: terraform validate

#       - name: Terraform Format Check
#         run: terraform fmt -check
      
#       - name: Azure login
#         id: login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

#       - name: Terraform Init
#         run: terraform init -backend-config=terraform-backend.tfvars
#         working-directory: terraform/storage
#         env:
#           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#           AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#         working-directory: terraform/storage
#         env:
#           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#           AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

